#pragma config(Sensor, S1,     light1,         sensorLightActive)
#pragma config(Sensor, S2,     light2,         sensorColorNxtRED)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          leopold,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Links 34, 67, S2
//Rechts 35, 66, S1

#pragma platform(NXT)

#include "remote_control.c";

long nLastXmitTimeStamp = nPgmTime;
long nDeltaTime = 0;

const int kMaxSizeOfMessage = 30;
const int INBOX = 5;


// Controleert of er een object voor het apparaat staat.
void measure_sonar()
{
	int ultrasonic = SensorValue[S4];
	nxtDisplayString(2, "snr value: %d", ultrasonic);
}


// Handmatige besturing via bluetooth.
void remote_control()
{
	TFileIOResult nBTCmdRdErrorStatus;
	int nSizeOfMessage;
	ubyte nRcvBuffer[kMaxSizeOfMessage];

	while(1){
		nSizeOfMessage = cCmdMessageGetSize(INBOX);

		if (nSizeOfMessage > kMaxSizeOfMessage)
			nSizeOfMessage = kMaxSizeOfMessage;
		if (nSizeOfMessage > 0){
			nBTCmdRdErrorStatus = cCmdMessageRead(nRcvBuffer, nSizeOfMessage, INBOX);
			nRcvBuffer[nSizeOfMessage] = '\0';
			string input = "";
			stringFromChars(input, (char *) nRcvBuffer);
			displayCenteredBigTextLine(4, input);

			switch(input){
				case "LEFT":
					turn_left();
					break;

				case "RIGHT":
					turn_right();
					break;

				case "DOWN":
					turn_backward();
					break;

				case "UP":
					move_forward();
					break;

				case "FIRE":
					// Vuurt een elastiekje af.
					break;

				case "A":
					// Terug naar automatisch.
					stop_motor();
					break;
			}
		}
	}
}


// Volgt de zwarte lijn automatisch.
void follow_line()
{
	measure_sonar();
	if (kruispunt){
		remote_control();
	}
}


task main()
{
	while(1){
		follow_line();
		wait1Msec(1);
	}
}
